/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 24 22:26:29 GMT 2026
 */

package com.bank;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.bank.Account;
import com.bank.TransferService;
import java.math.BigDecimal;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TransferService_ESTest extends TransferService_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TransferService transferService0 = new TransferService();
      Account account0 = new Account();
      BigDecimal bigDecimal0 = new BigDecimal((-426L));
      Account account1 = new Account();
      // Undeclared exception!
      try { 
        transferService0.transfer(account0, account1, bigDecimal0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Valor inv\u00E1lido
         //
         verifyException("com.bank.TransferService", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TransferService transferService0 = new TransferService();
      BigDecimal bigDecimal0 = BigDecimal.TEN;
      Account account0 = new Account();
      account0.deposit(bigDecimal0);
      Account account1 = new Account();
      transferService0.transfer(account0, account1, bigDecimal0);
      assertFalse(account1.equals((Object)account0));
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TransferService transferService0 = new TransferService();
      BigDecimal bigDecimal0 = BigDecimal.TEN;
      Account account0 = new Account();
      Account account1 = new Account();
      // Undeclared exception!
      try { 
        transferService0.transfer(account0, account1, bigDecimal0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Saldo insuficiente
         //
         verifyException("com.bank.Account", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      TransferService transferService0 = new TransferService();
      Account account0 = new Account();
      Account account1 = new Account();
      // Undeclared exception!
      try { 
        transferService0.transfer(account1, account0, (BigDecimal) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Valor inv\u00E1lido
         //
         verifyException("com.bank.TransferService", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      TransferService transferService0 = new TransferService();
      Account account0 = new Account();
      Account account1 = new Account();
      BigDecimal bigDecimal0 = new BigDecimal(0);
      // Undeclared exception!
      try { 
        transferService0.transfer(account1, account0, bigDecimal0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Valor inv\u00E1lido
         //
         verifyException("com.bank.TransferService", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      TransferService transferService0 = new TransferService();
      Account account0 = new Account();
      BigDecimal bigDecimal0 = BigDecimal.ONE;
      // Undeclared exception!
      try { 
        transferService0.transfer(account0, (Account) null, bigDecimal0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Conta nula
         //
         verifyException("com.bank.TransferService", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      TransferService transferService0 = new TransferService();
      Account account0 = new Account();
      BigDecimal bigDecimal0 = new BigDecimal(0);
      // Undeclared exception!
      try { 
        transferService0.transfer(account0, account0, bigDecimal0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Mesma conta
         //
         verifyException("com.bank.TransferService", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      TransferService transferService0 = new TransferService();
      BigDecimal bigDecimal0 = BigDecimal.ONE;
      // Undeclared exception!
      try { 
        transferService0.transfer((Account) null, (Account) null, bigDecimal0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Conta nula
         //
         verifyException("com.bank.TransferService", e);
      }
  }
}
