/*
 * This file was automatically generated by EvoSuite
 * Sat Jan 24 22:27:54 GMT 2026
 */

package com.bank.evosuite;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.bank.Account;
import java.math.BigDecimal;
import java.math.BigInteger;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Account_ESTest extends Account_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Account account0 = new Account();
      BigDecimal bigDecimal0 = new BigDecimal(2793L);
      account0.deposit(bigDecimal0);
      BigDecimal bigDecimal1 = BigDecimal.TEN;
      account0.withdraw(bigDecimal1);
      assertEquals((byte)10, bigDecimal1.byteValue());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Account account0 = new Account();
      BigDecimal bigDecimal0 = new BigDecimal((-3395L));
      // Undeclared exception!
      try { 
        account0.withdraw(bigDecimal0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Valor deve ser > 0
         //
         verifyException("com.bank.Account", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Account account0 = new Account();
      BigDecimal bigDecimal0 = new BigDecimal((-646.82379));
      // Undeclared exception!
      try { 
        account0.deposit(bigDecimal0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Valor deve ser > 0
         //
         verifyException("com.bank.Account", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Account account0 = new Account();
      byte[] byteArray0 = new byte[3];
      byteArray0[1] = (byte) (-38);
      BigInteger bigInteger0 = new BigInteger(byteArray0);
      BigDecimal bigDecimal0 = new BigDecimal(bigInteger0);
      account0.deposit(bigDecimal0);
      BigDecimal bigDecimal1 = account0.getBalance();
      assertNotSame(bigDecimal1, bigDecimal0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Account account0 = new Account();
      byte[] byteArray0 = new byte[3];
      byteArray0[2] = (byte)84;
      BigInteger bigInteger0 = new BigInteger(byteArray0);
      BigDecimal bigDecimal0 = new BigDecimal(bigInteger0);
      account0.deposit(bigDecimal0);
      BigDecimal bigDecimal1 = account0.getBalance();
      assertTrue(bigDecimal1.equals((Object)bigDecimal0));
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Account account0 = new Account();
      BigDecimal bigDecimal0 = new BigDecimal(172L);
      account0.deposit(bigDecimal0);
      BigDecimal bigDecimal1 = account0.getBalance();
      assertTrue(bigDecimal1.equals((Object)bigDecimal0));
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Account account0 = new Account();
      // Undeclared exception!
      try { 
        account0.deposit((BigDecimal) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Dep\u00F3sito inv\u00E1lido
         //
         verifyException("com.bank.Account", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Account account0 = new Account();
      // Undeclared exception!
      try { 
        account0.withdraw((BigDecimal) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Saque inv\u00E1lido
         //
         verifyException("com.bank.Account", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Account account0 = new Account();
      BigDecimal bigDecimal0 = account0.getBalance();
      // Undeclared exception!
      try { 
        account0.withdraw(bigDecimal0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Valor deve ser > 0
         //
         verifyException("com.bank.Account", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Account account0 = new Account();
      BigDecimal bigDecimal0 = BigDecimal.TEN;
      // Undeclared exception!
      try { 
        account0.withdraw(bigDecimal0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Saldo insuficiente
         //
         verifyException("com.bank.Account", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Account account0 = new Account();
      BigDecimal bigDecimal0 = BigDecimal.TEN;
      account0.deposit(bigDecimal0);
      account0.withdraw(bigDecimal0);
      assertEquals((byte)10, bigDecimal0.byteValue());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Account account0 = new Account();
      BigDecimal bigDecimal0 = account0.getBalance();
      // Undeclared exception!
      try { 
        account0.deposit(bigDecimal0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Valor deve ser > 0
         //
         verifyException("com.bank.Account", e);
      }
  }
}
